blockeraai/blockera

packages/blocks/core/js/index.js
packages/blocks/core/js/test/blocks-list.spec.js
packages/blocks/core/js/woocommerce-blocks-list.json
packages/blocks/core/js/woocommerce/index.js
packages/blocks/core/js/woocommerce/product-price/index.js
packages/blocks/core/php/functions.php

Feat: WooCommerce blocks support (base)

---

packages/editor/js/extensions/libs/block-states/components/item-opener.js

fix: icon name

---

packages/dev-cypress/js/support/commands.js
packages/editor/js/extensions/components/block-base.js
packages/editor/js/extensions/components/block-compatibility.js
packages/editor/js/extensions/components/utils.js
packages/editor/js/extensions/hooks/block-settings.js

Optimized BlockBase, BlockCompatibility, and block-settings Edit components with memoization.
the content attributes typing changes very slow!

Optimized content attribute typing original speed

---

packages/controls/js/libs/group-control/style.scss

repeater items action buttons does not showing on hover

Fix: repeater action buttons

---

packages/controls/js/libs/panel-body-control/components/powered-by.js
packages/dev-cypress/js/helpers/block-states.js
packages/dev-cypress/js/helpers/responsive.js
packages/dev-cypress/js/support/commands.js
packages/editor/js/components/editor-advanced-label/test/border.advanced-label-1.e2e.cy.js
packages/editor/js/components/editor-advanced-label/test/repeater.advanced-label-3.e2e.cy.js
packages/editor/js/extensions/components/block-partials.js
packages/editor/js/extensions/libs/block-card/components/block-card-wrapper.scss
packages/editor/js/extensions/libs/shared/index.js
packages/editor/js/extensions/libs/shared/style.scss

Feat: UX Enhancements 

---

packages/editor/js/extensions/libs/block-card/components/block-card-wrapper.scss
packages/editor/js/extensions/libs/block-card/test/sticky-block-card.e2e.cy.js

more tests for checking block sticky and also fix for block card design

Fix: Block card design and more tests

---

packages/editor/js/hooks/use-attributes/reducer.js

Optimize performance and fix useAttributes problems, because this problems could affect the repeater functionalities.

fix: mergeObject() use-case on set state

---

packages/editor/js/extensions/libs/block-card/components/block-card.scss
packages/editor/js/extensions/libs/block-card/components/breadcrumb.js

Small fixes and improvements for block card

Feat: Improvements and fixes for block card

---

packages/blockera/js/index.js
packages/editor/js/canvas-editor/bootstrap.js
packages/editor/js/canvas-editor/components/breakpoints/index.js
packages/editor/js/canvas-editor/index.js
packages/editor/js/canvas-editor/test/canvas-editor.e2e.cy.js
packages/editor/js/extensions/hooks/block-settings.js
packages/utils/js/is/index.js

Fix canvas editor rendering on Site Editor.

Fix Canvas editor rendering on Site Editor

---

blockera.php
changelog.txt

Feat: v0.9 Public Release version

---

packages/editor/js/canvas-editor/components/breakpoints/index.js

fix: set device preview state

---

blockera.php
changelog.txt

feat: v0.9.2 BUMP

---

composer.json
packages/dev-cypress/js/support/e2e.js
packages/editor/js/canvas-editor/test/canvas-editor.e2e.cy.js
packages/editor/js/style-engine/components/state-style.js
packages/editor/js/style-engine/hooks/use-computed-css-props.js
packages/editor/js/style-engine/test/style-engine.e2e.cy.js
packages/editor/php/StyleDefinitions/Layout.php

Temporary Optimize performance and functionalities of style engine

---

packages/blockera/CHANGELOG.md
packages/blockera/js/test/editor.bootstrap.e2e.cy.js
packages/blocks/core/js/wordpress/group/test/gap-type-gap-and-margin.e2e.cy.js
packages/editor/CHANGELOG.md
packages/editor/js/canvas-editor/test/canvas-editor.e2e.cy.js
packages/editor/php/StyleDefinitions/Layout.php
packages/editor/php/helpers.php
packages/editor/php/tests/TestHelpers.php

Inside CSS engine after changing selector, the generated style should be correct.

Bug: Style engine bug

---

README.md
blockera.php
packages/blockera/js/test/editor.woocommerce.e2e.cy.js
packages/blocks/core/js/wordpress/columns/test/block-attributes.blocks.e2e.cy.js
packages/controls/CHANGELOG.md
packages/controls/js/libs/base-control/style.scss
packages/editor/CHANGELOG.md
packages/editor/js/canvas-editor/components/preview.js
packages/editor/js/canvas-editor/style.scss
packages/editor/js/extensions/components/block-dropdown-all-menu.js
packages/editor/js/extensions/components/block-icon.js
packages/editor/js/extensions/components/style.scss
packages/editor/js/extensions/components/test/block-partials.e2e.cy.js
packages/editor/js/extensions/libs/flex-child/extension.js
packages/editor/js/extensions/libs/flex-child/style.scss
packages/editor/js/extensions/libs/shared/index.js
packages/editor/js/extensions/libs/typography/compatibility/text-align.js
packages/editor/js/extensions/libs/typography/test/text-align.compatibility.e2e.cy.js

Some small design improvements

Feat: Design improvements

---

packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/layout/styles.js
packages/editor/js/extensions/libs/layout/test/flex-layout.e2e.cy.js
packages/editor/php/StyleDefinitions/Layout.php

reported here: https://community.blockera.ai/bugs-mdhyb8nc/post/advanced-values-of-flex-layout-not-working-properly-wTCfgyDW4w1EoVK

fix: Advanced flex layout values issue

---

packages/blocks/core/CHANGELOG.md
packages/blocks/core/js/wordpress-blocks-list.json
packages/blocks/core/js/wordpress/index.js
packages/blocks/core/js/wordpress/spacer/index.js
packages/blocks/core/js/wordpress/spacer/test/block.inner-blocks.e2e.cy.js
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/size/compatibility/height.js
packages/editor/js/extensions/libs/size/test/height.compatibility.e2e.cy.js

Add support to core Spacer block: https://community.blockera.ai/feature-request-1rsjg2ck/post/spacer-block-support-pritFhuc8gbsXko

Feat: Spacer block support

---

packages/controls/CHANGELOG.md
packages/controls/js/libs/input-control/components/unit-input.js
packages/controls/js/libs/input-control/index.js
packages/controls/js/libs/input-control/test/input-control.cy.js

[Issue](https://community.blockera.ai/bugs-mdhyb8nc/post/the-width-feature-does-not-accepts-0-value-74lCJXSXBziXaqU) in Blockera community

fix: input control does not accepts 0 value

---

packages/blocks/core/CHANGELOG.md
packages/blocks/core/js/wordpress-blocks-list.json
packages/blocks/core/js/wordpress/home-link/index.js
packages/blocks/core/js/wordpress/home-link/test/block.blocks.e2e.cy.js
packages/blocks/core/js/wordpress/index.js
packages/blocks/core/js/wordpress/navigation-link/index.js
packages/blocks/core/js/wordpress/navigation-link/test/block.blocks.e2e.cy.js
packages/blocks/core/js/wordpress/navigation-submenu/index.js
packages/blocks/core/js/wordpress/navigation-submenu/test/block.blocks.e2e.cy.js
packages/blocks/core/php/wordpress/navigation-submenu/block.php
packages/blocks/core/php/wordpress/navigation-submenu/index.php
packages/editor/js/extensions/libs/block-card/components/block-card.js
packages/editor/js/extensions/libs/block-card/components/block-card.scss
packages/icons/js/library-ui/icons/block-navigation-submenu-container.svg
packages/icons/js/library-ui/icons/block-navigation-submenu-items.svg
packages/icons/js/library-ui/icons/index.js

Related feature request: https://community.blockera.ai/feature-request-1rsjg2ck/post/supporting-blocks-inside-navigation-block-MIcY979kIVCxkvU

Feat: Support Navigation Block inner blocks

---

packages/editor/CHANGELOG.md
packages/editor/js/extensions/components/block-partials.js
packages/editor/js/extensions/components/style.scss
packages/editor/js/extensions/components/test/block-partials.e2e.cy.js
packages/utils/js/portal/index.js

fix: Duplicate block card issue

---

packages/blocks/core/php/shared/attributes.php
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/base/config/typography.js
packages/editor/js/extensions/libs/layout/extension.js
packages/editor/js/extensions/libs/shared/index.js
packages/editor/js/extensions/libs/size/components/object-fit.js
packages/editor/js/extensions/libs/size/extension.js
packages/editor/js/extensions/libs/typography/bootstrap.js
packages/editor/js/extensions/libs/typography/compatibility/font-family.js
packages/editor/js/extensions/libs/typography/compatibility/font-weight.js
packages/editor/js/extensions/libs/typography/components/font-family.js
packages/editor/js/extensions/libs/typography/components/font-size.js
packages/editor/js/extensions/libs/typography/components/font-style.js
packages/editor/js/extensions/libs/typography/components/font-weight.js
packages/editor/js/extensions/libs/typography/components/index.js
packages/editor/js/extensions/libs/typography/components/text-decoration.js
packages/editor/js/extensions/libs/typography/components/text-transform.js
packages/editor/js/extensions/libs/typography/extension.js
packages/editor/js/extensions/libs/typography/styles.js
packages/editor/js/extensions/libs/typography/test/font-family.compatibility.e2e.cy.js
packages/editor/js/extensions/libs/typography/test/font-family.e2e.cy.js
packages/editor/js/extensions/libs/typography/test/font-size.compatibility.e2e.cy.js
packages/editor/js/extensions/libs/typography/test/font-size.e2e.cy.js
packages/editor/js/extensions/libs/typography/test/font-weight.compatibility.e2e.cy.js
packages/editor/js/extensions/libs/typography/test/font-weight.e2e.cy.js
packages/editor/js/extensions/libs/typography/type/typography-props.js
packages/editor/js/extensions/libs/typography/utils.js
packages/editor/js/hooks/use-advanced-label-props/test/use-advanced-label-props.e2e.cy.js
packages/editor/js/schemas/block-supports/typography-block-supports-list.json
packages/editor/php/StyleDefinitions/Typography.php

Related link of feature request: 
Tasks:

Feature: Font Family and Font Weight Options

---

packages/dev-cypress/blockera-pm.json
packages/dev-jest/blockera-pm.json
packages/dev-phpunit/blockera-pm.json
packages/dev-tools/blockera-pm.json

This PR syncs the package from the [blockera-pro](https://github.com/blockeraai/blockera-pro) repository.

Sync package from blockera-pro Repo

---

packages/editor/js/extensions/libs/shared/index.js
packages/editor/php/StyleDefinitions/Layout.php

fix: the flex-child wrong values

---

.github/build-plugin-zip/action.yml
.github/workflows/build-plugin-zip.yml
.github/workflows/bundle-size.yml
.github/workflows/create-demo-assets.yml
.github/workflows/create-demo-attachments.yml
bin/build-plugin-zip.sh

Add creation playground link in build-plugin-zip.yml workflow

feat: add playground link address

---

packages/blocks/core/CHANGELOG.md
packages/blocks/core/js/wordpress/image/index.js
packages/blocks/core/js/wordpress/image/test/block.inner-blocks.e2e.cy.js
packages/blocks/core/php/wordpress/image/block.php

Feat: Improve Image Block

---

packages/blocks/core/CHANGELOG.md
packages/blocks/core/js/wordpress/navigation-submenu/index.js
packages/blocks/core/php/wordpress/navigation-submenu/block.php

Feat: Improve Navigation blocks

---

.github/workflows/build-plugin-zip-tests.yml
.github/workflows/create-demo-attachments.yml
.github/workflows/php-unit-tests.yml
blockera.php
packages/blockera-admin/php/tests/AdminProviderTest.php
packages/blockera/CHANGELOG.md
packages/blockera/js/test/editor.woocommerce.e2e.cy.js
packages/blockera/php/Providers/AppServiceProvider.php
packages/wordpress/CHANGELOG.md
packages/wordpress/js/admin/helpers.js
packages/wordpress/js/admin/style.scss
packages/wordpress/php/Admin/Menu/Factory.php
phpunit.xml.dist

CI: check multiple php versions for more compatibility

---

README.md
readme.txt

Feat: Small fixes

---

composer.json
composer.lock
packages/editor/CHANGELOG.md
packages/editor/js/extensions/components/block-base.js
packages/editor/js/extensions/hooks/block-settings.js

- Ensured compatibility with the React.js rendering pipeline [[🔗 Bug](https://community.blockera.ai/bugs-mdhyb8nc/post/single-product-block-error-bXDiO88g7LsP0hV)].
- Fixed the block mode callback handler to improve functionality and reliability [[🔗 Bug](https://community.blockera.ai/bugs-mdhyb8nc/post/block-mode-switch-not-works-FsR1uwRuIcCakWp)].

Fixes some bugs on editor features

---

blockera.php
readme.txt

Feat: improve desc and optimize for search for WP.org

---

package-lock.json
package.json
packages/editor/CHANGELOG.md
packages/editor/js/extensions/hooks/block-settings.js

1. Handling errors with ErrorBoundary at the top of tree components in WordPress Editor.
2. Fix TypeError cannot call class as a function

Fix TypeError: cannot call class as a function

---

packages/data/CHANGELOG.md
packages/data/js/variables/color.js
packages/data/js/variables/spacing.js
packages/data/js/variables/utils.js
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/typography/styles.js

Reported bug: https://community.blockera.ai/bugs-mdhyb8nc/post/theme-defined-spacing-does-not-fall-back-to-wordpress-defaults-Ft6gpFAjwsMoNA8

fix: Error while current block theme have not variable settings

---

config/menu.php
experimental.config.json
packages/blockera-admin/CHANGELOG.md
packages/blockera-admin/js/style.scss
packages/blockera-admin/php/Providers/AdminAssetsProvider.php
packages/blockera-admin/php/hooks.php
packages/blockera/php/app.php
packages/blockera/php/hooks.php
packages/data/CHANGELOG.md
packages/data/js/variables/store/selectors.js
packages/editor/CHANGELOG.md
packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
packages/editor/php/StyleDefinitions/Divider.php
packages/editor/php/StyleDefinitions/Layout.php

1. fix: upgrade to pro menu link issue
2. enhancements for BaseStyleDefinition to setCss for registered and customized support id.
3. fix the LayoutStyleDefinition issue with "gap" css property.

Fix StyleEngine and Admin Styles and menus bugs

---

packages/blockera-admin/CHANGELOG.md
packages/blockera-admin/php/Providers/AdminAssetsProvider.php

Fix: Multiple issues and bugs

---

packages/blocks/core/php/shared/attributes.php
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/base/config/size.js
packages/editor/js/extensions/libs/shared/index.js
packages/editor/js/extensions/libs/size/extension.js
packages/editor/js/extensions/libs/size/styles.js
packages/editor/js/extensions/libs/size/test/box-sizing.e2e.cy.js
packages/editor/js/extensions/libs/size/types/size-props.js
packages/editor/js/schemas/block-supports/size-block-supports-list.json

Tasks:
Related feature request: https://community.blockera.ai/feature-request-1rsjg2ck/post/add-css-box-sizing-feature-oxkVk3kzg3ffPf1

Feat: Box Sizing feature in Size Block Section

---

.github/workflows/create-demo-attachments.yml
blockera.php
package.json
packages/blockera-admin/CHANGELOG.md
packages/blockera-admin/php/Providers/AdminAssetsProvider.php
packages/blockera-admin/php/hooks.php

Fix: Translation related edits

---

bin/generate-blockera-php.php
blockera.php
composer.json
composer.lock
config/app.php
config/menu.php
config/telemetry.php
packages/blockera/CHANGELOG.md
packages/blockera/php/Providers/AppServiceProvider.php
packages/blockera/php/app.php
packages/blockera/php/functions.php
packages/bootstrap/CHANGELOG.md
packages/bootstrap/php/Application.php
packages/bootstrap/php/BoundMethod.php
packages/bootstrap/php/ContextualBindingBuilder.php
packages/bootstrap/php/Contracts/Container.php
packages/bootstrap/php/Contracts/ContextualBindingBuilder.php
packages/bootstrap/php/RewindableGenerator.php
packages/bootstrap/php/ServiceProvider.php
packages/bootstrap/php/Util.php
packages/dev-phpunit/php/bootstrap.php
phpcs.xml

Implemented internal application container on server side to remove dependency on any external packages.
- Removed "illuminate\container" and  "psr/contrainer" packages. [Related Bug](https://community.blockera.ai/bugs-mdhyb8nc/post/php-conflict-about-illuminate-third-party-package-SXjus6bAuZffnPi)
- Renamed and strictly check for define constants to avoid conflicts with the third party WordPress plugins and themes. [Related Bug](https://community.blockera.ai/bugs-mdhyb8nc/post/warning-constant-blockera-version-already-defined-uvTMUjomFS8fELi)

Refactor: to fix reported bugs from users

---

packages/blockera-admin/CHANGELOG.md

Fix: Changelog text

---

packages/blockera-admin/php/Providers/AdminAssetsProvider.php
packages/blockera-admin/php/tests/TestAdminAssetsProvider.php

Fixed Site editor loading issue!
Added PHPUnit tests for admin asset loading!

Fix: admin assets loader

---

packages/blockera/CHANGELOG.md
packages/blockera/js/index.js
packages/editor/CHANGELOG.md
packages/editor/js/canvas-editor/bootstrap.js
packages/editor/js/extensions/hooks/block-settings.js
packages/editor/php/StyleDefinitions/BaseStyleDefinition.php

Detect performance bottlenecks and fix issues to improve speed and functionality.

Performance Optimization 

---

packages/editor/CHANGELOG.md
packages/editor/js/canvas-editor/helpers.js
packages/editor/js/canvas-editor/test/get-targets.spec.js
packages/telemetry/js/components/opt-in/opt-in.js

Fixes the duplicate preview icon issue reported by Hoang

Fix: Duplicate preview button

---

.github-playground.json
.github-pr-playground.example.json
.github/workflows/create-demo-attachments.yml

Improve playground to make it more easy to use.

Development: Playground demo improvements

---

packages/controls/CHANGELOG.md
packages/controls/js/libs/border-control/index.js
packages/controls/js/libs/border-control/style.scss
packages/controls/js/libs/border-radius-control/index.js
packages/controls/js/libs/border-radius-control/style.scss
packages/controls/js/libs/box-border-control/style.scss
packages/controls/js/libs/color-control/control.js
packages/controls/js/libs/color-indicator/color-indicator.js
packages/controls/js/libs/color-indicator/style.scss
packages/controls/js/libs/select-control/style.scss

Improvement for `Border Line` and `Border Radius` controls.

Feat: UX Improvements

---

packages/blocks/core/js/third-party/blocksy-about-me/test/about-me-block.blocksy.e2e.cy.js
packages/blocks/core/js/third-party/blocksy-breadcrumbs/test/breadcrumbs-block.blocksy.e2e.cy.js
packages/blocks/core/js/third-party/blocksy-contact-info/test/contact-info-block.blocksy.e2e.cy.js
packages/blocks/core/js/third-party/blocksy-search/test/search-block.blocksy.e2e.cy.js
packages/blocks/core/js/third-party/blocksy-share-box/test/share-box-block.blocksy.e2e.cy.js
packages/blocks/core/js/third-party/blocksy-socials/test/socials-block.blocksy.e2e.cy.js

Update Blocksy test because the Blocksy theme did changed the color variable labels officialy.

Blocksy Compatibility: Tests update

---

packages/controls/js/libs/box-position-control/components/side-item.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-all.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-bottom.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-horizontal.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-left.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-right.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-top.js
packages/controls/js/libs/box-spacing-control/components/margin/margin-vertical.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-all.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-bottom.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-horizontal.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-left.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-right.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-top.js
packages/controls/js/libs/box-spacing-control/components/padding/padding-vertical.js
packages/controls/js/libs/input-control/components/input.scss
packages/controls/js/libs/input-control/test/input-control.cy.js
packages/dev-cypress/js/support/commands.js
packages/editor/js/extensions/libs/position/test/box-position.e2e.cy.js
packages/editor/js/extensions/libs/spacing/test/spacing.e2e.cy.js
packages/utils/CHANGELOG.md
packages/utils/js/use-drag-value/index.js
packages/utils/js/use-drag-value/test/use-drag-value.spec.js

Improve drag value functionality to input controls for enhanced user interaction. The drage on input works inappropriate currently (based on our user research) and a threshold for drag needed. 
This feature allows value changes to be triggered after hitting a specific threshold, improving the user experience when adjusting margins, paddings, and box positions.
Key changes:
- Enhanced drag value functionality in input controls
- Updated margin and padding components to support drag value
- Improved box position control with drag value support
- Removed unused SCSS styles from input control
- Optimized use-drag-value hook implementation
Yes
The changes have been tested across all affected components:
- Box position controls
- Margin controls (all, top, bottom, left, right, vertical, …

Feat: Improve drag feature

---

packages/controls/CHANGELOG.md
packages/controls/js/libs/box-border-control/index.js
packages/controls/js/libs/box-border-control/style.scss

An issue that preview of border line feature is overlapping the inspector panel features

Fix: Border Line feature design issue

---

packages/blocks/core/php/shared/attributes.php
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/base/config/typography.js
packages/editor/js/extensions/libs/shared/index.js
packages/editor/js/extensions/libs/typography/extension.js
packages/editor/js/extensions/libs/typography/styles.js
packages/editor/js/extensions/libs/typography/type/typography-props.js
packages/editor/js/schemas/block-supports/typography-block-supports-list.json
packages/editor/php/StyleDefinitions/Typography.php

Related feature request in Blockera Community: https://community.blockera.ai/feature-request-1rsjg2ck/post/text-wrap-feature-g8g5NUHgr4PzDxv
Add Text Wrap feature to Typography Block Section. This enhancement includes:
- Implementation of text wrap controls in typography extension
- Updates to typography configuration and styles
- Addition of new typography attributes
- Integration with block supports list
- PHP-side support for text wrap features
Yes - This change adds new functionality while maintaining existing behavior.
The changes have been tested across:
- Typography block section functionality
- Integration with existing block supports
- Style generation and application
- PHP-side attribute handling

Feat: Text Wrap Feature

---

packages/controls/CHANGELOG.md
packages/controls/js/libs/border-control/index.js
packages/controls/js/libs/border-control/style.scss
packages/controls/js/libs/box-border-control/index.js
packages/controls/js/libs/box-spacing-control/style.scss
packages/controls/js/libs/color-control/style.scss
packages/controls/js/value-addons/components/control/value-addon-pointer.scss
packages/editor/js/extensions/libs/border-and-shadow/test/border.compatibility.e2e.cy.js
packages/editor/js/extensions/libs/border-and-shadow/test/border.e2e.cy.js

The goal of this PR is adding color variables support to Border Line feature.
@nguyenquanghoang Thank you for the suggestion

Feat: Add color variables support to Border Line feature

---

.patch/use-cleanup-styles-use-cases.js
experimental.config.json
packages/controls/js/libs/border-control/style.scss
packages/controls/js/value-addons/components/control/value-addon-pointer.scss
packages/controls/js/value-addons/components/variable/var-picker.js
packages/editor/CHANGELOG.md
packages/editor/js/extensions/components/block-app.js
packages/editor/js/extensions/components/block-base.js
packages/editor/js/extensions/libs/background/styles.js
packages/editor/js/extensions/libs/border-and-shadow/styles.js
packages/editor/js/extensions/libs/effects/styles.js
packages/editor/js/extensions/libs/flex-child/styles.js
packages/editor/js/extensions/libs/layout/styles.js
packages/editor/js/extensions/libs/mouse/styles.js
packages/editor/js/extensions/libs/position/styles.js
packages/editor/js/extensions/libs/size/styles.js
packages/editor/js/extensions/libs/spacing/styles.js
packages/editor/js/extensions/libs/typography/styles.js
packages/editor/js/hooks/use-cleanup-styles.js
packages/editor/js/style-engine/components/state-style.js
packages/editor/js/style-engine/css-generator.js
packages/editor/php/StyleDefinitions/Layout.php
packages/editor/php/StyleEngine.php
packages/editor/php/helpers.php
packages/wordpress/php/RenderBlock/V2/Transpiler.php

Feat: experimental style optimization on editor side

---

packages/blocks/core/js/wordpress/rss/test/functionality.blocks.e2e.cy.js
packages/controls/js/libs/box-spacing-control/style.scss
packages/controls/js/value-addons/components/control/value-addon-pointer.scss
packages/editor/CHANGELOG.md
packages/editor/php/StyleDefinitions/Layout.php
packages/wordpress/CHANGELOG.md

This is an issue reported by @nguyenquanghoang in [community](https://community.blockera.ai/discussions/post/is-this-a-bug-displaying-breakpoints-for-mobile-or-am-i-doing-something-8rjFtrlVdeR4l9E)

Fix: Flex layout on mobile

---

packages/editor/php/StyleDefinitions/Layout.php
packages/editor/php/StyleDefinitions/Size.php
packages/editor/php/StyleDefinitions/Spacing.php

To fix multiple detected issues on the style engine v2

Fix: Style engine v2 fixes

---

packages/blockera/CHANGELOG.md
packages/blockera/js/test/compatibility.blocksy.e2e.cy.js
packages/blockera/php/Compatibility/Themes/Blocksy/Blocksy.php
packages/controls/CHANGELOG.md
packages/controls/js/value-addons/index.js
packages/controls/js/value-addons/test/helpers.spec.js
packages/controls/js/value-addons/utils.js

Fix: Improve variable unlink + blocksy compatibility

---

packages/blocks/core/php/shared/attributes.php
packages/controls/CHANGELOG.md
packages/controls/js/libs/box-spacing-control/style.scss
packages/controls/js/libs/input-control/components/unit-input.js
packages/editor/CHANGELOG.md
packages/editor/js/extensions/components/block-base.js
packages/editor/js/extensions/libs/layout/components/gap.js
packages/editor/js/extensions/libs/layout/styles.js
packages/editor/js/style-engine/get-computed-css-props.js

fix: some reported bugs from users of Blockera community

---

packages/bootstrap/blockera-folder-sync.json
packages/classnames/blockera-folder-sync.json
packages/controls/blockera-folder-sync.json
packages/data-editor/blockera-folder-sync.json
packages/data/blockera-folder-sync.json
packages/dev-tools/blockera-folder-sync.json
packages/editor/blockera-folder-sync.json
packages/env/blockera-folder-sync.json
packages/icons/blockera-folder-sync.json
packages/storage/blockera-folder-sync.json
packages/utils/blockera-folder-sync.json
packages/wordpress/blockera-folder-sync.json

to sync some packages with blockera-site-toolkit

chore: modified blockera-folder-sync files

---

packages/blockera-admin/CHANGELOG.md
packages/blockera-admin/php/Providers/AdminAssetsProvider.php
packages/blockera/CHANGELOG.md
packages/blockera/php/Providers/EditorAssetsProvider.php
packages/bootstrap/CHANGELOG.md
packages/bootstrap/php/AssetsProvider.php
packages/wordpress/php/AssetsLoader.php

Feat: implements standalone infrastructure

---

.github/workflows/check-debugging-code.yml
cypress.config.js
packages/blocks/core/js/index.js
packages/blocks/core/js/test/blocks-list.spec.js
packages/bootstrap/js/index.js
packages/controls/js/context/test/control-context.spec.js
packages/controls/js/libs/background-control/test/background-control.cy.js
packages/controls/js/libs/color-picker-control/color-picker-control.js
packages/controls/js/libs/notice-control/stories/index.stories.js
packages/controls/js/libs/repeater-control/store/reducers/test/sort-item.spec.js
packages/controls/js/libs/repeater-control/test/repeater-control.cy.js
packages/controls/js/libs/toggle-select-control/style.scss
packages/dev-phpunit/php/bootstrap.php
packages/editor/js/canvas-editor/test/canvas-editor.e2e.cy.js
packages/editor/js/components/editor-advanced-label/test/box-position.advanced-label-4.e2e.cy.js
packages/editor/js/extensions/api/registration.js
packages/editor/js/extensions/components/performance-bottlenecks-detector.js
packages/editor/js/extensions/components/render-monitor.js
packages/editor/js/extensions/components/test/block-partials.e2e.cy.js
packages/editor/js/extensions/libs/effects/test/dividers.e2e.cy.js
packages/editor/js/hooks/use-attributes/test/use-attributes.e2e.cy.js
packages/editor/js/hooks/use-trace-update/index.js
packages/editor/js/style-engine/utils.js
packages/editor/js/test/block-supports-list.spec.js
packages/icons/js/icon.js
packages/storage/js/local-storage/index.js
packages/telemetry/js/components/bug-detector-and-reporter/sender.js
packages/utils/js/memo/index.js
packages/utils/js/object/index.js
packages/utils/php/functions.php

We need to detect debugging codes in `PHP`, `JS` and `tests` to remove them before merging codes into the master!

CI: Workflow to detect debugging codes

---

bin/build-plugin-zip.sh
packages/blockera/CHANGELOG.md
packages/blocks/core/CHANGELOG.md
packages/blocks/core/js/wordpress/column/test/functionality.build.e2e.cy.js

Fix: add the bootstrap directory into archive file

---

packages/editor/CHANGELOG.md
packages/editor/php/StyleDefinitions/Layout.php

Fix: Flex layout bug on breakpoints

---

packages/blockera-admin/CHANGELOG.md
packages/blockera-admin/js/style.scss

Fix: Design issue on admin pages.

---

packages/controls/js/libs/button/style.scss

This PR syncs the package from the [blockera-site-toolkit](https://github.com/blockeraai/blockera-site-toolkit) repository.

Sync package from blockera-site-toolkit Repo

---

packages/blocks/core/CHANGELOG.md
packages/blocks/core/js/wordpress/latest-comments/test/functionality.blocks-2.e2e.cy.js
packages/blocks/core/js/wordpress/rss/test/functionality.blocks-2.e2e.cy.js
packages/controls/CHANGELOG.md
packages/controls/js/libs/feature-wrapper/index.js
packages/controls/js/libs/feature-wrapper/style.scss
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/style-variations/components/block-styles.scss

Fix: Design fix and improvements

---

packages/controls/js/libs/feature-wrapper/style.scss
packages/controls/js/libs/modal/index.js
packages/editor/CHANGELOG.md

Fix: Modal design issue

---

.gitignore
packages/controls/CHANGELOG.md
packages/controls/js/libs/color-picker-control/components/color-pallet.scss
packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/block-card/block-states/states.js
packages/editor/js/extensions/libs/block-card/block-states/style.scss
packages/editor/js/extensions/libs/block-card/inner-blocks/components/item-header.js
packages/editor/js/extensions/libs/block-composite/components/categorized-items.js
packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
packages/editor/php/StyleDefinitions/Traits/WithDisplayValueTrait.php

fix: reported bugs from users 

---

packages/editor/CHANGELOG.md
packages/editor/js/extensions/libs/block-card/style-variations/components/block-styles.js
packages/editor/js/extensions/libs/block-card/style-variations/components/block-styles.scss
packages/editor/js/extensions/libs/block-card/style-variations/components/preview-panel.js
packages/editor/js/extensions/libs/block-card/style-variations/index.js

Feat: Style variations live preview

---

packages/blocks/core/blockera-folder-sync.json

Fixed blockera folder sync problems

chore: modified the blockera-folder-sync.json file

---

composer.lock
packages/env/php/functions.php

Minor improvements to standalone of consumer project.

chore: modified the experimental.config.json

---

packages/editor/CHANGELOG.md
packages/editor/js/style-engine/components/state-style.js

fix: the 7 responsive breakpoints problems in style engine
